#!/usr/bin/with-contenv bash

## Ubuntu
if [ -f /usr/bin/apt ]; then
    echo "\
        zsh \
        " >> /mod-repo-packages-to-install.list

fi
# Alpine
if [ -f /sbin/apk ]; then
    echo "\
    autossh \
    bash \
    bind-tools \
    dateutils \
    file \
    git \
    jq \
    moreutils \
    musl-locales \
    nano \
    net-tools \
    openssh \
    openvpn \
    p7zip \
    rclone \
    rsync \
    run-parts \
    sqlite \
    sudo \
    tini \
    tmux \
    util-linux \
    wget \
    xz \
    zsh \
    alpine-zsh-config \
    zsh-theme-powerlevel10k \
    " >> /mod-repo-packages-to-install.list
fi
