#!/usr/bin/with-contenv bash
# shellcheck shell=bash

USER_NAME=${USER_NAME:-linuxserver.io}

if [[ ! -z ${USER_HOME} ]]; then
    echo "[chg-userhome-sshconfig] moving authorized_keys to \"${USER_HOME}/.ssh/authorized_keys\""
    if [[ -f "/config/.ssh/authorized_keys" ]]; then
        if [[ ! -d "${USER_HOME}/.ssh" ]]; then
            mkdir -p "${USER_HOME}/.ssh"
        fi

        mv "/config/.ssh/authorized_keys" "${USER_HOME}/.ssh/authorized_keys"
        chmod 0700 "${USER_HOME}/.ssh"
        chmod 0600 "${USER_HOME}/.ssh/authorized_keys"
    fi

    lsiown -R "${USER_NAME}:${USER_NAME}" "${USER_HOME}"
fi
