#!/usr/bin/with-contenv bash
# shellcheck shell=bash

USER_NAME=${USER_NAME:-linuxserver.io}

if [[ ! -z ${PRIVATE_KEY_ECDSA} ]]; then
    [[ ! -d "/config/.ssh" ]] && mkdir --mode=0700 "/config/.ssh"

    echo -e "${PRIVATE_KEY_ECDSA}" | tee "/config/.ssh/id_ecdsa" > /dev/null
    chmod 0600 "/config/.ssh/id_ecdsa"
    ssh-keygen -y -f /config/.ssh/id_ecdsa | tee "/config/.ssh/id_ecdsa.pub" > /dev/null
fi

lsiown "${USER_NAME}":"${USER_NAME}" /config
